spring:
  application.name: digiseq-web-portal
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    hikari.connectionTimeout: 20000
    hikari.maximumPoolSize: 5
  flyway:
    locations: classpath:db/migration
server:
  port: 8090

client-org:
  days-until-marked-expiring-soon: 7

---
spring:
  config:
    activate:
      on-profile: test
  flyway:
    enabled: false
db:
  url: jdbc:postgresql://localhost:5432/postgres
  username: postgres
  password: postgres

---
spring:
  config:
    activate:
      on-profile: local
db:
  url: jdbc:postgresql://localhost:5432/postgres
  username: postgres
  password: postgres
