spring:
  application.name: digiseq-web-portal
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    hikari.connectionTimeout: 20000
    hikari.maximumPoolSize: 5
  flyway:
    locations: classpath:db/migration
server:
  port: 8090
---
spring:
  config:
    activate:
      on-profile: test
db:
  url: jdbc:postgresql://localhost:15432/postgres
  username: postgres
  password: postgres

